plugins {
    id "com.android.application"
}

android {
    namespace "org.alliance.smsbridge"
    compileSdk 35

    defaultConfig {
        applicationId "org.alliance.smsbridge"
        minSdk 26
        targetSdk 33
        versionCode 2
        versionName "0.1.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
